server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:23306/vex?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vex
    password: vex123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: NotificationServiceHikariPool
  rabbitmq:
    host: localhost
    port: 5672
    username: vex
    password: vex123

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.vex: DEBUG
    root: INFO